//: [Previous](@previous)
/*:
 ## [5. Longest Palindromic Substring](https://leetcode.com/problems/longest-palindromic-substring/)
 [__String__] [__Medium__]

 Given a string `s`, return _the longest palindromic substring_ in `s`.
 */
import BlindSwift

let solution = Solution()

print(solution.longestPalindrome1("babad"))
print(solution.longestPalindrome1("cbbd"))

print(solution.longestPalindrome2("babad"))
print(solution.longestPalindrome2("cbbd"))

print(solution.longestPalindrome3("babad"))
print(solution.longestPalindrome3("cbbd"))

print(solution.longestPalindrome3("abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababa"))
//: [Next](@next)
